version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: reviews-server-img
    container_name: reviews-server
    volumes:
      - .:/src/app
      - /src/app/node_modules
    ports:
      - "1128:1128"
    depends_on:
      - mongo
    env_file: .env
    environment:
      - MONGO_HOSTNAME=$MONGO_HOSTNAME
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    networks:
      - review-network
  mongo:
    image: mongo
    container_name: reviews-mongodb
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - review-network

networks:
    review-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local